services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      sidekiq:
        condition: service_started
    ports:
      - "9292:9292"
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: franco
      POSTGRES_PASSWORD: franco123
      POSTGRES_DB: fudoproducts
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U franco -d fudoproducts"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  redis:
    image: redis:latest
    networks:
      - my_network

  sidekiq:
    build: .
    command: bundle exec sidekiq -r "./lib/sidekiq_config.rb"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
